/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Sport } from "./Sport";
import { SportCountArgs } from "./SportCountArgs";
import { SportFindManyArgs } from "./SportFindManyArgs";
import { SportFindUniqueArgs } from "./SportFindUniqueArgs";
import { CreateSportArgs } from "./CreateSportArgs";
import { UpdateSportArgs } from "./UpdateSportArgs";
import { DeleteSportArgs } from "./DeleteSportArgs";
import { ArticleFindManyArgs } from "../../article/base/ArticleFindManyArgs";
import { Article } from "../../article/base/Article";
import { SportService } from "../sport.service";
@graphql.Resolver(() => Sport)
export class SportResolverBase {
  constructor(protected readonly service: SportService) {}

  async _sportsMeta(
    @graphql.Args() args: SportCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Sport])
  async sports(@graphql.Args() args: SportFindManyArgs): Promise<Sport[]> {
    return this.service.sports(args);
  }

  @graphql.Query(() => Sport, { nullable: true })
  async sport(
    @graphql.Args() args: SportFindUniqueArgs
  ): Promise<Sport | null> {
    const result = await this.service.sport(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Sport)
  async createSport(@graphql.Args() args: CreateSportArgs): Promise<Sport> {
    return await this.service.createSport({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Sport)
  async updateSport(
    @graphql.Args() args: UpdateSportArgs
  ): Promise<Sport | null> {
    try {
      return await this.service.updateSport({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Sport)
  async deleteSport(
    @graphql.Args() args: DeleteSportArgs
  ): Promise<Sport | null> {
    try {
      return await this.service.deleteSport(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Article], { name: "articles" })
  async findArticles(
    @graphql.Parent() parent: Sport,
    @graphql.Args() args: ArticleFindManyArgs
  ): Promise<Article[]> {
    const results = await this.service.findArticles(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
