/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SportService } from "../sport.service";
import { SportCreateInput } from "./SportCreateInput";
import { Sport } from "./Sport";
import { SportFindManyArgs } from "./SportFindManyArgs";
import { SportWhereUniqueInput } from "./SportWhereUniqueInput";
import { SportUpdateInput } from "./SportUpdateInput";
import { ArticleFindManyArgs } from "../../article/base/ArticleFindManyArgs";
import { Article } from "../../article/base/Article";
import { ArticleWhereUniqueInput } from "../../article/base/ArticleWhereUniqueInput";

export class SportControllerBase {
  constructor(protected readonly service: SportService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Sport })
  async createSport(@common.Body() data: SportCreateInput): Promise<Sport> {
    return await this.service.createSport({
      data: data,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Sport] })
  @ApiNestedQuery(SportFindManyArgs)
  async sports(@common.Req() request: Request): Promise<Sport[]> {
    const args = plainToClass(SportFindManyArgs, request.query);
    return this.service.sports({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Sport })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async sport(
    @common.Param() params: SportWhereUniqueInput
  ): Promise<Sport | null> {
    const result = await this.service.sport({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Sport })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSport(
    @common.Param() params: SportWhereUniqueInput,
    @common.Body() data: SportUpdateInput
  ): Promise<Sport | null> {
    try {
      return await this.service.updateSport({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Sport })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSport(
    @common.Param() params: SportWhereUniqueInput
  ): Promise<Sport | null> {
    try {
      return await this.service.deleteSport({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/articles")
  @ApiNestedQuery(ArticleFindManyArgs)
  async findArticles(
    @common.Req() request: Request,
    @common.Param() params: SportWhereUniqueInput
  ): Promise<Article[]> {
    const query = plainToClass(ArticleFindManyArgs, request.query);
    const results = await this.service.findArticles(params.id, {
      ...query,
      select: {
        content: true,
        createdAt: true,
        id: true,

        sport: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/articles")
  async connectArticles(
    @common.Param() params: SportWhereUniqueInput,
    @common.Body() body: ArticleWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      articles: {
        connect: body,
      },
    };
    await this.service.updateSport({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/articles")
  async updateArticles(
    @common.Param() params: SportWhereUniqueInput,
    @common.Body() body: ArticleWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      articles: {
        set: body,
      },
    };
    await this.service.updateSport({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/articles")
  async disconnectArticles(
    @common.Param() params: SportWhereUniqueInput,
    @common.Body() body: ArticleWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      articles: {
        disconnect: body,
      },
    };
    await this.service.updateSport({
      where: params,
      data,
      select: { id: true },
    });
  }
}
